Fix guild commands deployment
MAXOUXAX/Isabelle pull request #2
Opened 2024-11-19 12:26 UTC by ThomasRbn

2024-11-19 12:29 UTC, Ozraam commented
Looks good

2024-11-19 13:03 UTC, ThomasRbn commented
> Looks good

He said that's it's not good :(((

2024-11-19 15:30 UTC, Ozraam commented
In my heart it's good

2024-11-27 09:19 UTC, MAXOUXAX requested changes
Cette PR ne sera pas merge, je travaille sur un fix à ce problème qui ne reprends aucun élément de cette PR, la garder ouverte est donc inutile :)
Merci d'avoir relevé le problème cela dit :D

2024-11-29 14:11 UTC, closed without merging